### PR TITLE
Update nhl.json

### PR DESCRIPTION
**Pull request by CATColor1**

### CODE REVIEW

**Comment by jimniels** [comment]
Can you elaborate on why you changed all of these, where you sourced the information from, etc?

**Comment by CATColor1** [comment]
Yes. The reason why I changed all 30 NHL team colors is to ensure they are as accurate as possible. I have sources, though unfortunately not for all teams. I will list all of the official sources I have for some teams from NHL.com here, though:
Carolina Hurricanes: http://hurricanes.nhl.com/club/microhome.htm?location=/jersey
Chicago Blackhawks: http://blackhawks.nhl.com/club/page.htm?id=47745
Colorado Avalanche: http://avalanche.nhl.com/club/page.htm?id=32557
Columbus Blue Jackets: http://bluejackets.nhl.com/v2/ext/CBJ_LOGOS.pdf
Dallas Stars: http://2.cdn.nhle.com/nhl/images/upload/2013/06/STARS_UNIS_1000.jpg
New Jersey Devils: http://devils.nhl.com/club/page.htm?id=42037#24
New York Islanders: http://islanders.nhl.com/v2/ext/Islanders_Brand_Assests.pdf#page=3
Pittsburgh Penguins: http://penguins.nhl.com/v2/ext/pdf/15.16%20Sponsor%20Playbook/2015-16%20Partner%20Playbook%20-%20Brand%20Style%20Guide%20-%2019.pdf#page=4
Those are the only 8 teams for which I have official color information (albeit in Pantone colors). I'm still looking for the other 22 teams, though I have come across this website (for which I don't have access/credentials to): https://link.nhl.com/brandassets/register/

**Comment by CATColor1** [comment]
So, I guess the only team colors that should be updated (given the references I've provided) are the Carolina Hurricanes, Chicago Blackhawks, Colorado Avalanche, Columbus Blue Jackets, Dallas Stars, New Jersey Devils, New York Islanders, and Pittsburgh Penguins. The other 22 teams' colors should not be updated until official source information is found, if that helps.

**Comment by jimniels** [comment]
If those are the only ones that need updating, please open another PR for just those teams. Additionally, when colors are updated, the logo colors also need to be updated. Those are in the `.sketch` files. If you can't update them, please just know that I will have to do it manually myself and so it may take some time as I have lots of other things on my plate. Thanks!

**Pull request closed without merging**
